name: msf-lime
globals:
workflows:
  Workflow-TEST-Get-TEIs-from-DHIS2:
    name: Workflow TEST Get TEIs from DHIS2
    jobs:
      TEST-Get-TEIs-from-DHIS2:
        name: TEST Get TEIs from DHIS2
        adaptor: '@openfn/dhis2@v3.2.11'
        enabled: false
        globals:
        body: |
          get('trackedEntityInstances', {
            ou: 'l22DQq4iV3G',
            program: 'uGHvY5HFoLG',
            programStatus: 'ACTIVE'
            //filter: ['enrollmentStatus:Eq:ACTIVE'],
          }, state => {
            console.log('# of TEIs ::', state.data.trackedEntityInstances.length);
            console.log('TEI data ::', JSON.stringify(state.data)); 
            return state; 
          });
          
          
          
          // get('enrollments', {
          //   ou: 'l22DQq4iV3G',
          //   program: 'uGHvY5HFoLG',
          //   trackedEntityInstance: 'uDuQMpXynsZ'
          // }, state => {
          //   console.log('TEI data ::', JSON.stringify(state.data)); 
          //   return state; 
          // });
          
    triggers:
      Daily-@-6:00AM:
        type: cron
        cron_expression: '0 6 * * *'
    edges:
      Daily-@-6:00AM->TEST-Get-TEIs-from-DHIS2:
        source_trigger: Daily-@-6:00AM
        target_job: TEST-Get-TEIs-from-DHIS2
        condition: always
        condition_type: always
  