version: "3.8"

networks:
  ozone:
  web:
    external: true

services:
  gateway:
    image: gateway
    restart: "unless-stopped"
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - ozone
      - web

  frontend:
    image: frontend
    restart: "unless-stopped"
    depends_on:
      - backend
    networks:
      - ozone
      - web

  backend:
    image: backend
    restart: "unless-stopped"
    networks:
      - ozone
      - web

  db:
    image: db
    restart: "unless-stopped"
    networks:
      - ozone
      - web